version: '3'
services:
  graphql:
    environment: 
      - ROOT_DIR="usr/src/src"
      - ELASTICSEARCH_HOST=10.120.43.120:9200
    build: ./
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
